### ISSUE TITLE
Program change Problem

### ISSUE THREAD

**Issue by Johan-v** [MarkCWirt/MIDIUtil#13]
Hello, I'm experimenting with MIDIUtil and I like it, thank you!
I found a problem with program changes.
I think in MidiFile.py following is missing for program changes.
        if self.header.numeric_format == 1:
            track += 1

Regards,
Johan

**Comment by MarkCWirt** [comment]
Sorry it's taken a little while to get back to you (I was off the grid on vacation).

Thanks for reporting this. I'll investigate. I need to push a new version to include the pitch-bend on the develop branch, and I'll include this if needed.

Thanks again.

**Comment by Wolf-at-SO** [comment]
(I hope you had a nice holiday.)

Maybe this is a different issue, but the title suggests that it's "closely related": I observed that a program change on one track in a 2-track midi file affects both tracks, but not if I also use different channels. This script can be used to show the issue.

~~~~
# -*- coding: utf-8 -*-

from midiutil import MIDIFile

tr_A = 0
ch_A = 0

tr_B = 1
ch_B = 0

MyMIDI = MIDIFile(2, adjust_origin = True)
MyMIDI.addTempo(-1, time=1, tempo=120)

MyMIDI.addProgramChange(tr_A, ch_A, time=1, program=40)

MyMIDI.addNote(tr_A, ch_A, pitch=50, time=1, duration=4, volume=100)
MyMIDI.addNote(tr_A, ch_A, pitch=54, time=5, duration=4, volume=100)

MyMIDI.addProgramChange(tr_B, ch_B, time=1, program=17)

MyMIDI.addNote(tr_B, ch_B, pitch=62, time=3, duration=4, volume=100)
MyMIDI.addNote(tr_B, ch_B, pitch=66, time=7, duration=4, volume=100)

with open("midiutil-i13.mid", "wb") as output_file:
    MyMIDI.writeFile(output_file)
~~~~

If I change `ch_B = 0` into `ch_B = 1` I have two different instruments in the resulting MIDI file.

Is this intended? Sorry if this is a dumb question, I'm not really familiar with MIDI internals.

**Comment by MarkCWirt** [comment]
Hmm. I'll have to think about this one.

I assume you're using the latest version (i.e., it is defaulting to a format 2 file)?

**Comment by Wolf-at-SO** [comment]
@MarkCWirt yes, the latest version, I discovered your utility only a couple of days ago, so I think my download was a fresh one.

**Comment by Wolf-at-SO** [comment]
I'm even not sure if the issue isn't caused by MediaPlayer, sorry I didn't think of that. Here is a hex-dump of the MIDI produces by above code:


![midiutil-i13-hex-dump](https://user-images.githubusercontent.com/29630128/28784970-4a5bac0c-7615-11e7-88ea-1c9d2c6e01d0.png)

**Comment by Johan-v** [comment]
Hello,

I had a problem with keysignatures in file format 1
I changed a setting: see below and now it works.

Regards, 

Johan

    def addKeySignature(self, track, time, accidentals, accidental_type, mode,
                        insertion_order=0):
        '''
        Add a Key Signature to a track

        :param track: The track to which this should be added
        :param time: The time at which the signature should be placed
        :param accidentals: The number of accidentals in the key signature
        :param accidental_type: The type of accidental
        :param mode: The mode of the scale

        The easiest way to use this function is to make sure that the symbolic
        constants for accidental_type and mode are imported. By doing this:

        .. code::

            from midiutil.MidiFile import *

        one gets the following constants defined:

        * ``SHARPS``
        * ``FLATS``
        * ``MAJOR``
        * ``MINOR``

        So, for example, if one wanted to create a key signature for a minor
        scale with three sharps:

        .. code::

            MyMIDI.addKeySignature(0, 0, 3, SHARPS, MINOR)
        '''
        if self.header.numeric_format == 1:
            track = 0   <---------------------- This works
        #    track += 1

**Comment by imallenyang** [comment]
First off, thank you for creating this Utility, but I think file_format = 2 does not really work.
from midiutil import MIDIFile
import subprocess

degrees  = [60, 62, 64, 65, 67, 69, 71, 72, 71, 69, 67, 65, 64, 62, 60]  # MIDI note number
a = 0
b = 1
time     = 0    # In beats
duration = 1   # In beats
tempo    = 140   # In BPM
volume   = 100  # 0-127, as per the MIDI standard

MyMIDI = MIDIFile(2, adjust_origin = False, file_format = 2)  # One track, defaults to format 1 (tempo track is created
                      # automatically)

MyMIDI.addTempo(0, time, 60)
MyMIDI.addTrackName(0, time, "A")
MyMIDI.addTempo(1, time, 140)
MyMIDI.addTrackName(1, time, "B")

MyMIDI.addProgramChange(a, a, time, 6)
for i, pitch in enumerate(degrees):
    MyMIDI.addNote(0, 0, pitch, time + i, duration, volume)

MyMIDI.addProgramChange(b, b, time, 0)
for i, pitch in enumerate(degrees):
    MyMIDI.addNote(1, 1, pitch, time + i, duration, volume)



with open("major-scale.mid", "wb") as output_file:
    MyMIDI.writeFile(output_file)

subprocess.run(["open", "major-scale.mid"])

when this code snippet is executed, none of the notes on either track were added.

**Comment by imallenyang** [comment]
First off, thank you for creating this Utility, but I think file_format = 2 does not really work.
`from midiutil import MIDIFile
import subprocess

degrees = [60, 62, 64, 65, 67, 69, 71, 72, 71, 69, 67, 65, 64, 62, 60] # MIDI note number
a = 0
b = 1
time = 0 # In beats
duration = 1 # In beats
tempo = 140 # In BPM
volume = 100 # 0-127, as per the MIDI standard

MyMIDI = MIDIFile(2, adjust_origin = False, file_format = 2) # One track, defaults to format 1 (tempo track is created
# automatically)

MyMIDI.addTempo(0, time, 60)
MyMIDI.addTrackName(0, time, "A")
MyMIDI.addTempo(1, time, 140)
MyMIDI.addTrackName(1, time, "B")

MyMIDI.addProgramChange(a, a, time, 6)
for i, pitch in enumerate(degrees):
MyMIDI.addNote(0, 0, pitch, time + i, duration, volume)

MyMIDI.addProgramChange(b, b, time, 0)
for i, pitch in enumerate(degrees):
MyMIDI.addNote(1, 1, pitch, time + i, duration, volume)

with open("major-scale.mid", "wb") as output_file:
MyMIDI.writeFile(output_file)

subprocess.run(["open", "major-scale.mid"])`

when this code snippet is executed, none of the notes on either track were added.

**Comment by imallenyang** [comment]
First off, thank you for creating this Utility, but I think file_format = 2 does not really work.
`from midiutil import MIDIFile
import subprocess

degrees = [60, 62, 64, 65, 67, 69, 71, 72, 71, 69, 67, 65, 64, 62, 60] # MIDI note number
a = 0
b = 1
time = 0 # In beats
duration = 1 # In beats
tempo = 140 # In BPM
volume = 100 # 0-127, as per the MIDI standard

MyMIDI = MIDIFile(2, adjust_origin = False, file_format = 2) # One track, defaults to format 1 (tempo track is created
# automatically)

MyMIDI.addTempo(0, time, 60)
MyMIDI.addTrackName(0, time, "A")
MyMIDI.addTempo(1, time, 140)
MyMIDI.addTrackName(1, time, "B")

MyMIDI.addProgramChange(a, a, time, 6)
for i, pitch in enumerate(degrees):
MyMIDI.addNote(0, 0, pitch, time + i, duration, volume)

MyMIDI.addProgramChange(b, b, time, 0)
for i, pitch in enumerate(degrees):
MyMIDI.addNote(1, 1, pitch, time + i, duration, volume)

with open("major-scale.mid", "wb") as output_file:
MyMIDI.writeFile(output_file)

subprocess.run(["open", "major-scale.mid"])`
when this code snippet is executed, none of the notes on either track were added.

**Comment by MarkCWirt** [comment]
Hey Johan,

I've searched for definitive information on where this meta-event should be written. I've not found any place where it says that key signature should be written to the first track, but because this works for you, I'm going to take your word for it and make the change...
