### ISSUE TITLE
Time signatures inconsistently recognized in third-party programs

### ISSUE THREAD

**Issue by Michael-F-Ellis** [MarkCWirt/MIDIUtil#14]
First off, thanks for creating and maintaining MIDIUtil!.  It's made a huge difference in getting my typographic notation project up and running.  I found the documentation clear and thorough and the code seems to be doing all the right things.  My project, tbon, is at https://github.com/Michael-F-Ellis/tbon

Now then to my issue (which I suspect is not a problem in MIDIUtil).

My notation supports flexibly changing meter, beat note and tempo on a measure to measure basis.  The midi files I'm producing sound correct when played with QMidi and QMidi correctly displays the changing tempi and meters.  However, the same files opened as a project in MuseScore, Reaper, and Logic have various problems with meter and tempo:

  * MuseScore get the durations right but seems to ignore the time signatures in favor of its own choices. The playback sounds right.
  * Reaper omits some but not all time signatures and gets the durations of some notes correspondingly wrong.
  * Logic X omits some time signatures but plays all durations correctly.

**I'm trying to find out if there's anything wrong with the way I'm using MIDIUtil to create the files before submitting bug reports to MuseScore, Reaper and Logic.**

My test case is relatively simple: 1 measure each of 4/4, 6/8, 2/4, 6/8, 2/4 (5 measures in all). Here's a hex dump of the file. GitHub won't let me attach midi files to issue comments.

```
$ hexdump examples/meter.mid
0000000 4d 54 68 64 00 00 00 06 00 01 00 02 03 c0 4d 54
0000010 72 6b 00 00 00 53 00 ff 58 04 04 02 18 08 00 ff
0000020 51 03 07 a1 20 9e 00 ff 58 04 06 03 24 08 00 ff
0000030 51 03 0b 71 b0 8f 00 ff 58 04 02 02 18 08 00 ff
0000040 51 03 07 a1 20 8f 00 ff 58 04 06 03 24 08 00 ff
0000050 51 03 0b 71 b0 8f 00 ff 58 04 02 02 18 08 00 ff
0000060 51 03 07 a1 20 00 ff 2f 00 4d 54 72 6b 00 00 00
0000070 b8 00 90 3c 65 87 40 80 3c 65 00 90 3e 65 87 40
0000080 80 3e 65 00 90 40 65 87 40 80 40 65 00 90 41 65
0000090 87 40 80 41 65 00 90 43 65 82 40 80 43 65 00 90
00000a0 45 65 82 40 80 45 65 00 90 43 65 82 40 80 43 65
00000b0 00 90 43 65 82 40 80 43 65 00 90 45 65 82 40 80
00000c0 45 65 00 90 43 65 82 40 80 43 65 00 90 48 65 87
00000d0 40 80 48 65 00 90 48 65 87 40 80 48 65 00 90 43
00000e0 65 82 40 80 43 65 00 90 45 65 82 40 80 45 65 00
00000f0 90 43 65 82 40 80 43 65 00 90 43 65 82 40 80 43
0000100 65 00 90 45 65 82 40 80 45 65 00 90 43 65 82 40
0000110 80 43 65 00 90 48 65 87 40 80 48 65 00 90 48 65
0000120 87 40 80 48 65 00 ff 2f 00
```

Here's the input file to my program:

```
$ cat examples/meter.tba
/* Changing meter and tempo. Constant eighth-note duration. */
/* 4/4  */
T=120
B=4 c d e f |

/* 6/8 (tempo reduced to 2/3) */
B=4. t=0.6667 gag gag |

/* 2/4 (tempo restored) */
B=4 t=1.0 c c |

/* 6/8  (tempo reduced to 2/3 */
B=4. t=0.6667 gag gag |

/* 2/4 (tempo restored) */
B=4 t=1.0 c c |
```

And here's part of my code that inserts key, tempo, and time signature events 

```
    MyMIDI = MIDIFile(1, adjust_origin=True)  # One track
    for m in meta:
        if m[0] == 'T':
            MyMIDI.addTempo(track, m[1], m[2])
        elif m[0] == 'K':
            time = m[1]
            sf, mi = m[2]
            mode = MINOR if mi == 1 else MAJOR
            accidentals = abs(sf)
            acc_type = SHARPS if sf > 0 else FLATS
            #print("Inserting key signature at time {}".format(time))
            #print(accidentals, acc_type, mode)
            MyMIDI.addKeySignature(track, time, accidentals, acc_type, mode)
        elif m[0] == 'M':
            ## Time signature
            time = m[1]
            numerator = m[2]
            denominator = m[3]
            ## midi denominator must be specified as a power of 2
            midi_denom = {2:1, 4:2, 8:3}[denominator]
            ## We want to make the midi metronome match beat duration.
            ## This requires recognizing compound meters
            ## See http://midiutil.readthedocs.io/en/1.1.3/class.html
            ## for discussion of arguments to addTimeSignature()
            ## including clocks_per_tick.
            if denominator == 8 and (numerator % 3 == 0):
                metro_clocks = 36
            elif denominator == 4:
                metro_clocks = 24
            elif denominator == 2:
                metro_clocks = 48

            MyMIDI.addTimeSignature(track, time,
                                    numerator,
                                    denominator=midi_denom,
                                    clocks_per_tick=metro_clocks)
 ```

Finally, here's what MuseScore 2.1 produces when the file is imported.  The pitches and durations are mathematically correct but it clearly has it's own mind about meter.  Measure 2 should be 6/8, measure 3 should be 2/4, measure 4 should be 6/8, and measure 5 should be 2/4.  As I mentioned above Logic and Reaper have different errors.  I include the MuseScore result here mainly to show what notes are in the file.

![meter_example](https://user-images.githubusercontent.com/6699301/32344307-cfd28e26-bfdc-11e7-891d-df525ccbd7fb.png)

Thanks for reading this far!
Mike

**Comment by Michael-F-Ellis** [comment]
SOLVED: I didn't understand that midi beats are interpreted in terms of quarter notes no matter what the time signature. 

After revising my parser/evaluator (not the utilization of MIDUUtil shown above), I now get correct results importing into MuseScore, Reaper, and Logic Pro X.  QMidi still works, too. I was also able to eliminate the need to specify tempo changes when the meter changes, so the input file is now simpler:

```
/* 4/4  */
T=120
B=4 c d e f |

/* 6/8  */
B=4. gag gag |

/* 2/4  */
B=4 c c |

/* 6/8  */
B=4. gag gag |

/* 2/4 */
B=4 c c |
```

When the midi file it produces is imported to MuseScore, I now get a correct result:

![meter2](https://user-images.githubusercontent.com/6699301/32409370-f5926708-c180-11e7-868a-f2668c37f4f8.png)

May I suggest a small revision to the docs to clarify that 'beats' is really 'quarter-note durations' ?

**Comment by MarkCWirt** [comment]
Michael,

I think it's a good idea to update the documentation, as this is somewhat confusing (heck, 
even I get confused about it!).

I've updated the documentation (which you can see [here](http://midiutil.readthedocs.io/en/latest/class.html#midiutil.MidiFile.MIDIFile.addTimeSignature) ). If you think that makes things a *little* more understandable, I'll close the ticket down.

**Comment by Michael-F-Ellis** [comment]
Thanks, Mark. My problem, though,  wasn't with addTimeSignature(). It was that I was taking the phrase 'time(in beats)' literally in computing what to specify for the time and duration arguments to addNote(). Things started working for me once I figured out that the start time and duration were really multiples of quarter notes.

So I think the doc change that would be most helpful would be to state that relationship explicitly in some prominent place, perhaps with a brief example.  In my test case above, the correct start times for the notes in the first two measures are: 0, 1 , 2 , 3  | 4,  4.5,  5,   5.5,  6.0,  6.5 | ...  but I was originally computing the second measure as 4, 4.33, 4.66,   5 5.33 5.66 |  because I was trying to express it as musical beats.

I agree it's a confusing subject.

Cheers,
Mike
