### ISSUE TITLE
MIDI file with file_format = 0

### ISSUE THREAD

**Issue by ShupingR** [MarkCWirt/MIDIUtil#15]
Hi, regarding the file_format, I was able to generate a MIDI file with `MyMIDI = MIDIFile(1, file_format=0)`, and the output has a single track. However, the document only mentioned that "Both format 1 (the default) and format 2 files are supported", and format 0 wasn't included. I am kinda new to MIDI, and please let me know if I misunderstood anything here. Thank you.

**Comment by MarkCWirt** [comment]
This is correct.

When I wrote the library I originally only supported format 2, but I later learned that this wasn't really widely adopted and has been deprecated to an extent.

Format 1 and 2 are both multi-track formats. In format 1 there is a special meta-event track where certain event types are written (time signatures, for example). The notes and events themselves are written to the other tracks. This a two-track format 1 file would really have three track object.

Format 2 is a little simpler; it's like a bunch of independent tracts concatenated together.

Format 0 is a simple, single-track format, but I haven't implemented that yet. If shouldn't be too difficult, but I have not had much time devote to this project lately. If people request it I'll look into supporting it.

Kind of the meta-issue is that I'm not a member of the MIDI association and as such don't have access to the definitive standards documentation. So supporting something like this tends to be a bit trail-and-error, trying to peace together the the information from what can be found publicly.
