### ISSUE TITLE
“Module not found”? What do you mean?

### ISSUE THREAD

**Issue by SgtPepperArc360** [MarkCWirt/MIDIUtil#47]
Hi!

So, I was recently testing out a python code in Microsoft Visual Studio Code, and the cloned git is in my Documents\GitHub folder, so I was able to work it from there. The only problem that comes between me and that python code is that I keep on getting an error saying there is “No module named midiutil”.
Errr, yes there is; I know it's there, and I know I installed it! What do you mean there is no module? Oh, wait. I was told elsewhere that Visual Studio always fails to recognize the location of the module. Do you have a way around this?

The python code in question is a script for a soul drum groove. I even used the Debug on the python codes in the examples folder and got that same error. Am I doing something wrong?

**Comment by FlipperPA** [comment]
Howdy! This library was written for Python 2, which might be part of the problem. I forked the library and ported it to Python 3 a few years ago. Feel free to give it a try: https://github.com/flipperpa/midi-writer

**Comment by SgtPepperArc360** [comment]
**Yeah, no. That is not my point. You need to help me find a way around the ModuleNotFoundError error.**

Here is the code:
```
from midiutil import MIDIFile

track = 0
channel = 9  # Drums channel
time = 0  # Start time in beats
tempo = 100  # BPM
volume = 100  # Max volume

MyMIDI = MIDIFile(1)
MyMIDI.addTempo(track, time, tempo)

kick = 36
snare = 38
closed_hh = 42
open_hh = 46
tambourine = 54

for bar in range(16):
    time = bar * 4  # Each bar starts at multiples of 4 beats
    # Kick on 1 and the "and" of 3
    MyMIDI.addNote(track, channel, kick, time, 0.25, volume)  # Beat 1
    MyMIDI.addNote(track, channel, kick, time + 2.5, 0.25, volume)  # "And" of 3
    # Snare on beats 2 and 4
    MyMIDI.addNote(track, channel, snare, time + 1, 0.25, volume)  # Beat 2
    MyMIDI.addNote(track, channel, snare, time + 3, 0.25, volume)  # Beat 4
    # Hi-hat on all eighth notes
    for eighth in range(8):
        MyMIDI.addNote(track, channel, closed_hh, time + (eighth * 0.5), 0.25, volume)

for bar in range(16):
    time = bar * 4
    MyMIDI.addNote(track, channel, tambourine, time + 1, 0.25, volume)  # Beat 2
    MyMIDI.addNote(track, channel, tambourine, time + 3, 0.25, volume)  # Beat 4

for bar in range(16):
    time = bar * 4
    MyMIDI.addNote(track, channel, snare, time + 1.5, 0.1, 60)  # Ghost note after beat 2
    MyMIDI.addNote(track, channel, snare, time + 3.5, 0.1, 60)  # Ghost note after beat 4

for bar in [7, 15]:
    time = bar * 4
    MyMIDI.addNote(track, channel, snare, time + 3.5, 0.25, volume)  # Strong snare hit on the fill
    MyMIDI.addNote(track, channel, open_hh, time + 3.75, 0.25, volume)  # Open hi-hat hit

for bar in [12, 13]:
    time = bar * 4
    MyMIDI.addNote(track, channel, kick, time, 0.25, volume)  # Kick on 1
    MyMIDI.addNote(track, channel, snare, time + 1, 0.25, volume)  # Snare on 2
    MyMIDI.addNote(track, channel, closed_hh, time + 1.5, 0.25, volume)  # Hi-hat on off-beat

MyMIDI.addNote(track, channel, snare, 63, 1, volume)  # Final hit at bar 16

with open("soul_drum_medley.mid", "wb") as output_file:
    MyMIDI.writeFile(output_file)
```

**Comment by FlipperPA** [comment]
Excuse me, I do not *need* to do anything. I just tried to offer the suggestion that you might not want to use Python 2.x, which hit its end-of-life date almost five years ago. Take it or leave it. Good luck.

**Comment by AFYifan** [comment]
``
